/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trvoid.tps;

public class App {
    private int serverAllowedTps = 500;

    private void sendRequest() {
        try {
            Thread.sleep(1000L / serverAllowedTps);
        } catch (InterruptedException e) {
            // DO NOTHING
        }
    }
    public void test(int remainingCount, int allowedTps, boolean sleepOnOverAllowedTps) {
        TpsInfo tpsInfo = new TpsInfo(allowedTps);

        int overAllowedTpsCount = 0;

        long startTime = System.currentTimeMillis();

        while (remainingCount > 0) {
            if (remainingCount % 100 == 0) {
                System.out.println(String.format("Remaining count = [%04d]", remainingCount));
            }

            if (tpsInfo.incrementRequestCount(sleepOnOverAllowedTps)) {
                sendRequest();
                remainingCount--;
            } else {
                System.out.println(String.format("  ** Over allowed TPS count = [%04d]", ++overAllowedTpsCount));
                try {
                    Thread.sleep(500L);
                } catch (InterruptedException e) {
                    // DO NOTHING
                }
            }
        }

        long elapsedTime = System.currentTimeMillis() - startTime;

        System.out.println(String.format("Elapsed time: %d millis", elapsedTime));
    }

    public static void main(String[] args) {
        App app = new App();
        app.test(1000, 100, true);
    }
}
